### ISSUE TITLE
Publish artifacts to maven central for 0.9.0 release?

### ISSUE THREAD

**Issue by mzamani1** [square/keywhiz#426]
Hi, it looks like 0.9.0 was released here on GitHub, but never published to maven central. Could that be done please?

**Comment by mcpherrinm** [comment]
@mbyczkowski You wanna do this?  If not I can do it later this week

**Comment by mbyczkowski** [comment]
Yes, I can look into that. I think I ran into release issues the last time. though, so maybe we'll just cut a new minor/patch release.

**Comment by mzamani1** [comment]
@mcpherrinm @mbyczkowski hey, any movement on this? Another pain point for us has been the lack of an artifact for the CLI, if that could be published as well that’d be awesome.

**Comment by mbyczkowski** [comment]
Currently, publishing to maven is broken and I haven’t quite figured out why.

Once we figure it out, we’ll gladly accept a PR to publish CLI as well :)

**Comment by mzamani1** [comment]
@mbyczkowski @mcpherrinm Is there more info around what aspect of maven publishing is broken, that someone else would be able to help with if there's a need?

**Comment by mbyczkowski** [comment]
@mzamani1 with #499 (and appropriate local config), but I can push artifacts to nexus's staging repo, but what's still missing is GPG-signing of artifacts and JavaDocs. Once all that is in place, I hope, we can cut release.

We'll probably scrub 0.9.0 and 0.10.0 (since we've tagged the repo and set pom to `0.10.0-SNAPSHOT` already) and go straight to 0.11.0.

**Comment by mbyczkowski** [comment]
@mzamani1 keywhiz artifacts have been published (0.10.1), e.g. you can see the new server version at https://mvnrepository.com/artifact/com.squareup.keywhiz/keywhiz-server/0.10.1
