### ISSUE TITLE
Question about upgrading from 0.8 to 0.10.1

### ISSUE THREAD

**Issue by FlavioImbertDomingos** [square/keywhiz#552]
We are running v0.8 o Keywhiz. 

Is there anything that we should be aware if I try to upgrade to v0.10.1? 
Is the upgrade straight forward (besides the Java upgrade)? 
Is there any issue during the upgrade that I should be aware?

Thank you so much in advance,

Flavio.

**Comment by mbyczkowski** [comment]
The biggest breaking changes are probably dropping support for H2 and PostgreSQL, so if you're not using those you should be fine.

We have also introduced row-level HMACs to protect records from DB tampering, but it requires a backfill to the database in order to be used (optionally you can disable it by adding `rowHmacCheck: disabled` to the config).

Other than that, you should check out the [CHANGELOG](https://github.com/square/keywhiz/blob/master/CHANGELOG.md).

**Comment by FlavioImbertDomingos** [comment]
Great, thank you!

> row-level HMACs to protect records from DB tampering

I am not using it. Where can I get more information about it?

Thank you so much.

**Comment by mbyczkowski** [comment]
@alokmenghrajani do you have more information about row-level HMAC feature and potential impact for people upgrading from older versions?

**Comment by FlavioImbertDomingos** [comment]
Mat,

Another question.. We are using 0.8 in PCI area. The compliance people is asking me if my version 0.8 has any know vulnerability. They can find and CVE for Keywhiz.. I am trying to delay the upgrade as much as I can since it will be a little trick for me (HSM client install, etc) at this moment. Let me know if the new releases are fixing any known vulnerability.
Best regards,
Flavio.

**Comment by mcpherrinm** [comment]
Some of Keywhiz's dependencies have had CVEs, such as jackson-databind.
We haven't evaluated if those are applicable to Keywhiz, but it is best to
keep upgraded.

Re: row-level hmacs.  You can leave validation turned off to avoid any
impact.  It is a new feature to reduce attack surface, by preventing
database modifications.
In order to turn it on, upgrading users must backfill existing entries to
have the HMACs applied to them.  I think there's instructions on doing that
in the github PRs, not sure offhand.  Alok would know
