### ISSUE TITLE
Need better compile instructions

### ISSUE THREAD

**Issue by cgswong** [square/keywhiz#78]
I'm running into the error:
`[ERROR] Failed to execute goal org.codehaus.mojo:sql-maven-plugin:1.5:execute (default) on project keywhiz-model: FATAL: password authentication failed for user "root" -> [Help 1]`
When trying to compile per the instructions, `mvn package -am -pl server`. How do I get around this please?

Also, the instructions need to be improved as there are too many assumptions such as you need to do `git clone [repo] && cd [repo]` and then start the build. Copying once the above issue is fixed the remainder will be smoother.

**Comment by sul3n3t** [comment]
This error is coming from the keywhiz-model maven module. It creates the PostgreSQL database `keywhizdb_test` and runs migrations, so jOOQ can run its code generation. In particular, that plugin emitting the error is attempting to authenticate to the database as [the current user](https://github.com/square/keywhiz/blob/master/model/pom.xml#L52). I recommend against running as root.

There's some instruction about installing PostgreSQL for development/test on the [Setup part](https://square.github.io/keywhiz/#setup) of the website.

We're working on making the database support more flexible (originally it was only PostgreSQL). The plan is to use H2 by default for the test/build environment. Since H2 is an in-memory, embedded database, there won't be any additional installation necessary.

I'll add something about running `git clone` to the website. What other instructions did you have in mind?

**Comment by hshyamh4** [comment]
Hi ,As per the link https://square.github.io/keywhiz/#setup ,i did the instructions but when i execute "mvn package -am -pl server" command my tests getting failed because of  org.flywaydb.core.api.FlywayException: Unable to drop "public"."accessgrants"

Can you help me out.

**Comment by sul3n3t** [comment]
@hshyamh4 I'm afraid that's not enough information for me to help you. Can you provide more of the stack trace? Ultimately, (flyway)[http://flywaydb.org/] is trying to run migrations and drop the existing tables at some point. It is unable to drop the `accessgrants` table from postgres for some reason. It could be an authentication problem, but the error message doesn't really say.

**Comment by hshyamh4** [comment]
Thanks for taking time and replying back,
I debugged the code and i came to know login name to the database is current user of the local machine.

Some of the places i did changes like(most of the places in pom.xml)

From:

 <configuration>
          <driver>org.postgresql.Driver</driver>
          <url>jdbc:postgresql:postgres</url>
          <username>${user.name}</username>
          <autocommit>true</autocommit>
          <sqlCommand>
            DROP DATABASE IF EXISTS keywhizdb_test;
            CREATE DATABASE keywhizdb_test;
          </sqlCommand>
        </configuration>


To:

 <configuration>
          <driver>org.postgresql.Driver</driver>
          <url>jdbc:postgresql:postgres</url>
          <username>postgres</username>
         <password>postgres</password>
          <autocommit>true</autocommit>
          <sqlCommand>
            DROP DATABASE IF EXISTS keywhizdb_test;
            CREATE DATABASE keywhizdb_test;
          </sqlCommand>
        </configuration>

Note:I gave full permissions to the user 'postgres'.

From some where in the application ${user.name} is referring other than form files.
In 'keywhiz-development.yaml' file when i try to add password it is not taking.
Test cases in keywhiz-server are getting failed because of authentication failed with Postgres 
My local machine user name is symaelakapalli, application is trying to login into postgres using my local machine name.

Can you help me please.

**Comment by hshyamh4** [comment]
![failed](https://cloud.githubusercontent.com/assets/12181092/7875180/39512fbe-05d7-11e5-9104-6ea1bb178241.png)

**Comment by sul3n3t** [comment]
Ah, I see. This is from the [sql-maven-plugin](http://mojo.codehaus.org/sql-maven-plugin/usage.html) configured [here in model/pom.xml](https://github.com/square/keywhiz/blob/master/model/pom.xml#L52). It's attempting to login to PostgreSQL as the current user. That can be changed by the highlighted line from that link. It assumes you don't require a password, but you can add a `<password>some_password</password>` line after the username if necessary. I only recommend doing that for a development/test database that is not network-accessible, of course.
